example/client/src/main.ts
plugins/org.eclipse.glsp.ide.editor/META-INF/MANIFEST.MF
plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ExportDiagramHandler.java
plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPDiagramEditorPart.java
plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPEditorRegistry.java
plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPServerManager.java
plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/di/EclipseEditorActionDispatcher.java
plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDynamicContribution.java
releng/org.eclipse.glsp.ide.releng.target/r2020-09.target
releng/org.eclipse.glsp.ide.releng.target/r2020-09.tpd

- An injector instance should correspond to a single client-connection,
as it contains some network-specific singleton instances that are not
meant to be shared/reused
- Start the server on any available port, to avoid conflicts between
different languages or parallel Eclipse IDE instances
Fixes #1
Fixes #2

[1] A Single injector is used for all editors (per editorPart ID)

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/ChromiumSelectionFunction.java
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java

Workaround for https://github.com/eclipse-glsp/glsp/issues/162
* add a custom browser function that notifies the RCP code when a mouse
down has occurred in the browser
* we will use this information to set the focus to the browser, if it is
not already the focus control
Signed-off-by: Johannes Faltermeier <jfaltermeier@eclipsesource.com>

Focus issue when opening two editor side-by-side #162

---

server/example/org.eclipse.glsp.ide.workflow.editor/WorkflowEditor.launch
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/ChromiumKeyBindingFunction.java
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/ChromiumSelectionFunction.java
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java

- Do not dispose browser functions, they are disposed with the browser
-- Also provide dedicated method for subclasses to install functions
- Fix launch config to choose a workspace-relative path location
-- Previous location depended on selected project in Eclipse
-- Previous location was always in Git-controlled area
Fixes eclipse-glsp/glsp/issues/182

#182: Do not dispose browser functions as they are auto-disposed

---

client/examples/workflow-webapp/LICENSE
client/examples/workflow-webapp/package.json
client/lerna.json
client/package.json
client/packages/ide/LICENSE
client/packages/ide/package.json
client/yarn.lock

Also add  update script to root package.json. The update script can be executed with `yarn upgrade:next`
Also: add missing license files to sub packages

#227 Use concrete next version instead of tag

---

Jenkinsfile
client/examples/workflow-webapp/package.json
client/package.json
client/packages/ide/package.json
client/yarn.lock

Revert back to using next tags after identifying issues for glsp-dependent projects that occurred with eclipse-glsp/glsp/issues/227.
We still want to maintain a "yarn upgrade:next" script in all repositories.
Requires https://github.com/eclipse-glsp/glsp-client/pull/118

Revert #227

---

client/.prettierrc
client/.vscode/extensions.json
client/.vscode/settings.json
client/examples/workflow-webapp/.eslintrc.js
client/examples/workflow-webapp/src/main.ts
client/examples/workflow-webapp/tsconfig.json
client/package.json
client/packages/ide/.eslintrc.js
client/packages/ide/src/base/eclipse-glsp-diagram-server.ts
client/packages/ide/src/features/copy-paste/copy-paste.ts
client/packages/ide/src/features/invoke-delete/invoke-delete.ts
client/packages/ide/src/features/keep-alive/keep-alive.ts
client/packages/ide/tsconfig.json
client/yarn.lock

- Use remote configuration instead of project-specific configuration.
- Use prettier instead of  the typescript-hero/editor-config/css-formatter extension set
- Reformat code with prettier
Part of eclipse-glsp/glsp/issues/377

#377 Switch to glsp-configuration package

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/di/IdeActionDispatcher.java
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/initialization/DefaultModelInitializationConstraint.java

closes https://github.com/eclipse-glsp/glsp/issues/435
As already mentioned in the issue, this PR fixes the:
- `ModelInitializationConstraint` so it waits for a `SetModelAction` instead of a `UpdateModelAction` to be marked as initialized
- Move the `editor.setInjector` method from the constructor to it's own method, to ensure that the IdeActionDispatcher is fully initialized by the DI before waiting `CompletableFuture`'s are resumed

#435 Fix Navigation from marker to affected element is no longer working

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPEditorRegistry.java
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java

This is a proposed fix for https://github.com/eclipse-glsp/glsp/issues/556
The idea behind the fix is to a) make access to the clientidToDiagramEditor Map thread safe and b) to turn off the ActionDispatcher when the editor is about to be closed. This way any actions that are still sent from the client are ignored after the editor was removed from the GLSPEditorRegistry.

GLSP Server Error when closing GLSP Eclipse Editor #556

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/ChromiumKeyBindingFunction.java

Fixes https://github.com/eclipse-glsp/glsp/issues/678

Apply KeyBindingFunction also for WebView2

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java

Fixes https://github.com/eclipse-glsp/glsp/issues/688
If simplified the `getFileName` method.

#688: Fix NPE in GLSPDiagramEditor#getFilePath

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/handlers/ExternalBrowserDebugHandler.java

The previous approach relied on `PlatformUI.getWorkbench().getBrowserSupport().getExternalBrowser().openURL()`, which opens the default handler of .html files (at least in Windows).
This is replaced by a hopefully more reliable approach to open the operating system's browser using java.awt.Desktop.
Closes https://github.com/eclipse-glsp/glsp/issues/743
How to test (e.g., in a Windows VM):
1. Set Windows default handler of `.html` files to something different than the browser: ![Screenshot from 2022-09-23 15-46-16](https://user-images.githubusercontent.com/1155551/191975210-32aa2e8f-d3ae-4e13-ba39-8e0a960628fc.png)
2. Open an example diagram in the WorkflowEditor
3. Start the main menu action Diagram -> Debug (External Browser)
4. Verify that the system's browser correctly opens the …

GH-743 Change approach to open operating system browser

---

.github/workflows/codeql-analysis.yml
Jenkinsfile
README.md
client/.gitignore
client/examples/workflow-webapp/package.json
client/package.json
client/packages/ide/package.json
client/yarn.lock

Update lerna and minimum node version
- https://github.com/eclipse-glsp/glsp/issues/676: 
Update to lerna 6 and set node 14 as minimum engine version
- https://github.com/eclipse-glsp/glsp/issues/812:
Improve yarn scripts
- Remove linting from prepare step
- Add dedicated :ci scrips for testing and linting
- Add 'all' script on root level
- Consistently sort scripts ascending
- https://github.com/eclipse-glsp/glsp/issues/680: 
Update to latest `@eclipse-glsp/config` version
- https://github.com/eclipse-glsp/glsp/issues/794: Update Jenkinsfile to
- directly include the npm deploy step instead of spawning a new dedicated job
- enable error reporting when master builds fail

Repo housekeeping

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/IdeGLSPClient.java

Fixes https://github.com/eclipse-glsp/glsp/issues/856
The session gets already closed when the part is closed, see `org.eclipse.glsp.ide.editor.ui.GLSPDiagramEditor.notifyAboutToBeDisposed()`.

Do not dispose client session twice

---

Jenkinsfile

Apparently the  config of the eclipseglsp/ci:alpine-v4.0 image does not allow proper synching with rsync and ssh. Therefore we execute the p2 deployment in separate job with a proper ssh configuration

Fix P2 deployment

---

CHANGELOG.md
server/example/org.eclipse.glsp.ide.workflow.editor/src/org/eclipse/glsp/ide/workflow/editor/WorkflowGLSPEclipseModule.java
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/actions/handlers/IdeSelectActionHandler.java
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/actions/handlers/IdeSelectAllActionHandler.java
server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java

This can best be tested by setting a breakpoint in the `org.eclipse.ui.internal.e4.compatibility.SelectionService`.
Fixes https://github.com/eclipse-glsp/glsp/issues/899
Contributed on behalf of STMicroelectronics

Propagate the GLSP diagram selection to the Eclipse SelectionService

---

server/releng/org.eclipse.glsp.ide.releng.target/r2021-09_minimum_baseline.target
server/releng/org.eclipse.glsp.ide.releng.target/r2021-09_minimum_baseline.tpd

Align GLSP version of minimum base line target with the default target. Follow-up of #72

Update GLSP version of minimum baseline target

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPEditorRegistry.java

This modifies the GLSPEditorRegistry to run editor.notifyAboutToBeDisposed without synchronization.
Fixes [ fixes Deadlock when saving by closing dirty editor (Eclipse IDE integration) #916 ](https://github.com/eclipse-glsp/glsp/issues/916)

Reduce 'synchronized' scope of GLSPEditorRegistry.partClosed

---

client/README.md
client/packages/ide/README.md
server/README.md

- Update outdated information sections in READMEs
- Update build badges

Update eclipse-integration READMEs

---

client/examples/workflow-webapp/src/app.ts
client/yarn.lock
server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.target
server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.tpd

- Update GLSP dependencies
- Make use of GLSPWebSocketProvider in workflow example
Part of https://github.com/eclipse-glsp/glsp/issues/77
---
Testing:
- To simulate interrupts, you can use the corresponding testing branch [`issues/77-testing`](https://github.com/eclipse-glsp/glsp-eclipse-integration/tree/issues/77-testing). This automatically interrupts the example twice with an timeout of 5s in between.

GLSP-77: Allow WebSocket connections to reconnect after interrupt

---

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPServerManager.java

Fix that resources with a symlink in the path are resolved by Jetty when running on Windows to prevent 404 error in the GLSP editor.

GLSP-1085 Fix Jetty 404 error on a symlinked path on Windows
