Jenkinsfile, pom.xml, releng/org.eclipse.glsp.ide.feature/.gitignore, releng/org.eclipse.glsp.ide.feature/.project, releng/org.eclipse.glsp.ide.feature/.settings/org.eclipse.core.resources.prefs, releng/org.eclipse.glsp.ide.feature/.settings/org.eclipse.m2e.core.prefs, releng/org.eclipse.glsp.ide.feature/build.properties, releng/org.eclipse.glsp.ide.feature/feature.xml, releng/org.eclipse.glsp.ide.feature/pom.xml, releng/org.eclipse.glsp.ide.releng.target/r2020-09.target, releng/org.eclipse.glsp.ide.releng.target/r2020-09.tpd, releng/org.eclipse.glsp.ide.repository/category.xml, releng/org.eclipse.glsp.ide.repository/pom.xml, releng/pom.xml
Part of eclipse-glsp/glsp/issues/156
=> #156 Setup & deploy P2 updatesite

releng/org.eclipse.glsp.ide.feature/feature.xml
=> #156: Remove dependencies for update site

releng/org.eclipse.glsp.ide.repository/category.xml
Follow-up for eclipse-glsp/glsp/issues/156
=> Add source feature to ide.repository plugin

server/plugins/org.eclipse.glsp.ide.editor/META-INF/MANIFEST.MF
=> #179: Export internal package for re-use

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPServerManager.java
Fixes https://github.com/eclipse-glsp/glsp/issues/215
=> #215: Ensure correct resource directory loading in server manager

server/plugins/org.eclipse.glsp.ide.editor/META-INF/MANIFEST.MF, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPServerManager.java, server/releng/org.eclipse.glsp.ide.releng.target/r2020-09.target, server/releng/org.eclipse.glsp.ide.releng.target/r2020-09.tpd
- Extract resolving into dedicated method for easier customization
=> #215: Fix issue on resource base resolving on Windows

server/plugins/org.eclipse.glsp.ide.editor/META-INF/MANIFEST.MF, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPServerManager.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/internal/utils/SystemUtils.java, server/releng/org.eclipse.glsp.ide.releng.target/r2020-09.target, server/releng/org.eclipse.glsp.ide.releng.target/r2020-09.tpd
=> #215: Get rid of additional dependency for Eclipse Integration

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java
- Add method to validate if the EditorInput has the correct expected type. 
- Add protected methods to customize the widegtid, clientId and partName generation in subclasses
- Remove the path argument from the setupBrowser() method. Some subclasses might need more than one filepath or even no file path at all.
Fixes eclipse-glsp/glsp/issues/375
=> #375 Improve extendibility of `GlspDiagramEditor`

client/examples/workflow-webapp/src/app.ts, client/examples/workflow-webapp/src/di.config.ts, client/package.json, client/packages/ide/src/features/copy-paste/copy-paste.ts, client/packages/ide/src/features/invoke-delete/invoke-delete.ts, client/yarn.lock, server/releng/org.eclipse.glsp.ide.releng.target/r2021-03.target, server/releng/org.eclipse.glsp.ide.releng.target/r2021-03.tpd
Based on https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/56
=> #690 Update to lastest client/protocol version

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/ChromiumKeyBindingFunction.java
Fixes https://github.com/eclipse-glsp/glsp/issues/719
=> Execute command async to avoid JRE error

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/IdeGLSPClient.java
Fixes https://github.com/eclipse-glsp/glsp/issues/759
=> Do not dispose session if another proxy is connected

server/example/org.eclipse.glsp.ide.workflow.editor/.checkstyle, server/plugins/org.eclipse.glsp.ide.editor/.checkstyle, server/releng/org.eclipse.glsp.ide.feature/.checkstyle, server/releng/org.eclipse.glsp.ide.repository/.checkstyle
Closes https://github.com/eclipse-glsp/glsp/issues/751
=> GH-751 Remove local file paths from .checkstyle files

server/pom.xml, server/releng/org.eclipse.glsp.ide.releng.target/pom.xml
This is needed to build with Java 17.
Part of https://github.com/eclipse-glsp/glsp/issues/750
Signed-off-by: Olaf Lessenich <olessenich@eclipsesource.com>
=> Update tycho maven version to 2.7.5 and remove `includePackedArtifacts`

.github/workflows/codeql-analysis.yml, Jenkinsfile, client/examples/workflow-webapp/src/app.ts, client/yarn.lock
Part of https://github.com/eclipse-glsp/glsp/issues/766
=> Upgrade to latest GLSP client version

server/example/org.eclipse.glsp.ide.workflow.editor/src/org/eclipse/glsp/ide/workflow/editor/WorkflowGLSPEclipseModule.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/gmodel/operations/IdeGModelPasteOperationHandler.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/BrowserFocusControlInstaller.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/BrowserFunctionInstaller.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/BrowserKeyBindingForwarderInstaller.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/ChromiumKeyBindingFunction.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/utils/SWTUtil.java, server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.target, server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.tpd
- Minor refactoring to browser functions to make them more generic
Relates to https://github.com/eclipse-glsp/glsp/issues/864
=> Update to latest nightly and new OperationHandler API

server/example/org.eclipse.glsp.ide.workflow.editor/plugin.xml, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/BrowserContextMenuInstaller.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java
* Add browser function that fires on context menu request
* Add example for custom context menu in workflow diagram
Fixes https://github.com/eclipse-glsp/glsp/issues/978 Fixes https://github.com/eclipse-glsp/glsp/issues/969
Contributed on behalf of STMicroelectronics
=> Fix context menu for Edge in Windows

client/package.json, client/yarn.lock
- Update to TS5 and inversify 6  
- Part of https://github.com/eclipse-glsp/glsp/issues/1022
=> Update to latest client and server versions

client/yarn.lock, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java, server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.target, server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.tpd
https://github.com/eclipse-glsp/glsp/issues/979
=> GLSP-979: Add support for 'deselectAll' in SelectAction

client/yarn.lock
Update to latest client version which introduces the Event API Part of eclipse-glsp/glsp/issues/1050
=> GLSP-1050: Update to latest client version

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/utils/UIUtil.java
fixes https://github.com/eclipse-glsp/glsp/issues/1108
=> Eclipse Integration: can't start plugin without running workbench

client/examples/workflow-webapp/src/app.ts, client/yarn.lock, server/example/org.eclipse.glsp.ide.workflow.editor/src/org/eclipse/glsp/ide/workflow/editor/WorkflowGLSPEclipseModule.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/actions/handlers/IdeMessageActionHandler.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/actions/handlers/IdeStatusActionHandler.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/handlers/IdeActionHandler.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramComposite.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditorStatusBar.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/utils/IdeMessageUtil.java, server/releng/org.eclipse.glsp.ide.releng.target/r2021-09_minimum_baseline.target, server/releng/org.eclipse.glsp.ide.releng.target/r2021-09_minimum_baseline.tpd, server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.target, server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.tpd
Adapt codebase to client changes for eclipse-glsp/glsp/issues/1116 Part of eclipse-glsp/glsp/issues/1116
Requires: https://github.com/eclipse-glsp/glsp-client/pull/288
=> GLSP-1116 Revise model loading

Jenkinsfile, client/.vscode/settings.json, client/examples/workflow-webapp/package.json, client/examples/workflow-webapp/tsconfig.json, client/package.json, client/packages/ide/package.json, client/packages/ide/src/features/copy-paste/copy-paste-module.ts, client/packages/ide/src/features/delete/delete-module.ts, client/packages/ide/src/features/fallback/fallback-module.ts, client/packages/ide/src/index.ts, client/packages/ide/tsconfig.json, client/tsconfig.json, client/yarn.lock, server/example/org.eclipse.glsp.ide.workflow.editor/META-INF/MANIFEST.MF, server/example/org.eclipse.glsp.ide.workflow.editor/pom.xml, server/plugins/org.eclipse.glsp.ide.editor/META-INF/MANIFEST.MF, server/plugins/org.eclipse.glsp.ide.editor/pom.xml, server/pom.xml, server/releng/org.eclipse.glsp.ide.feature/feature.xml, server/releng/org.eclipse.glsp.ide.feature/pom.xml, server/releng/org.eclipse.glsp.ide.releng.target/pom.xml, server/releng/org.eclipse.glsp.ide.releng.target/r2021-09_minimum_baseline.target, server/releng/org.eclipse.glsp.ide.releng.target/r2021-09_minimum_baseline.tpd, server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.target, server/releng/org.eclipse.glsp.ide.releng.target/r2022-12.tpd, server/releng/org.eclipse.glsp.ide.releng.target/r2023-09.target, server/releng/org.eclipse.glsp.ide.releng.target/r2023-09.tpd, server/releng/org.eclipse.glsp.ide.repository/pom.xml, server/releng/pom.xml
Part of https://github.com/eclipse-glsp/glsp/issues/1179 Part of https://github.com/eclipse-glsp/glsp/issues/1320
- Update to latest GLSP nightlies
- Fix nightly deployment by changing the build back to snapshot versions
- Update to latest dev configs
- Switch to composite ts build
- Add proper debuggable feature ids to eclipse feature modules
=> Update to latest next versions

.gitignore, Jenkinsfile, client/.gitignore, client/package.json, client/yarn.lock
=> Fix Jenkins build

Jenkinsfile, client/packages/ide/src/features/copy-paste/copy-paste-module.ts, client/packages/ide/src/features/delete/delete-module.ts, client/packages/ide/src/features/fallback/fallback-module.ts, client/packages/ide/src/index.ts, client/packages/ide/src/utils/url-parameters.ts
Fix copyright headers and linting
=> Fix copyright headers

server/example/org.eclipse.glsp.ide.workflow.editor/src/org/eclipse/glsp/ide/workflow/editor/OpenWorkflowViewerHandler.java, server/example/runtime/test/example1.wf, server/example/runtime/test/example2.wf, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/GLSPEditorRegistry.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/clipboard/ui/DisplayClipboardService.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/di/IdeActionDispatcher.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/handlers/ExternalBrowserDebugHandler.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/handlers/IdeActionHandler.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/initialization/AbstractModelInitializationConstraint.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/initialization/DefaultModelInitializationConstraint.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/BrowserContextMenuInstaller.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/BrowserFocusControlInstaller.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/BrowserKeyBindingForwarderInstaller.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/FocusAwareBrowser.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramComposite.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditor.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDiagramEditorStatusBar.java, server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/ui/GLSPDynamicContribution.java
Improve customizability through more protected methods and fields
Also update workflow example files
=> Improve customizability through more protected methods and fields

server/example/runtime/test/example1.wf, server/example/runtime/test/example2.wf
Align example ids with the expected ids of the  playwright tests
Part of https://github.com/eclipse-glsp/glsp/issues/1369
=> GLSP-1369: Update example1.wf

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/IdeGLSPClient.java
Fixes https://github.com/eclipse-glsp/glsp/issues/1413
- Build on the latest nightly target platform where Guava is no longer included
- Check that session behavior still works as expected
=> Remove guava from eclipse-integration server

server/plugins/org.eclipse.glsp.ide.editor/src/org/eclipse/glsp/ide/editor/IdeGLSPClient.java
See https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/104#issuecomment-2456413019
Fixes https://github.com/eclipse-glsp/glsp/issues/1413
=> Ensure session map is thread safe and avoid concurrent modification
